/* Ischemic Heart Lab: structured educational content and module renderers. */
(() => {
  "use strict";

  const esc = value => String(value).replace(/[&<>\"]/g, ch => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[ch]));
  const routeButton = (route, label) => `<button class="route-link" type="button" data-route="${route}">${label}</button>`;
  const tts = (title, body, extra="") => `<section class="section tts-unit" data-bookmark-title="${esc(title)}" data-tts-label="${esc(title)}">${extra}<div class="section-head"><h2>${title}</h2></div>${body}</section>`;
  const callout = (kind, title, body) => `<div class="callout ${kind}"><strong>${title}</strong>${body}</div>`;
  const table = (heads, rows) => `<div class="table-wrap"><table><thead><tr>${heads.map(h=>`<th>${h}</th>`).join("")}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`;
  const card = (title, body, cls="") => `<article class="card ${cls}"><h3>${title}</h3>${body}</article>`;

  function hero({eyebrow,title,intro,chips=[],visual="coronary"}){
    return `<section class="hero tts-unit" data-bookmark-title="${esc(title)}" data-tts-label="${esc(title)}"><div class="hero-copy"><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p class="lead">${intro}</p><div class="chip-row">${chips.map(c=>`<span class="chip">${c}</span>`).join("")}</div></div><div class="hero-visual" aria-hidden="true">${heroSvg(visual)}</div></section>`;
  }

  function heroSvg(type){
    if(type==="plaque") return `<svg viewBox="0 0 430 270"><defs><linearGradient id="vessel" x1="0" x2="1"><stop stop-color="#ffd7d9"/><stop offset="1" stop-color="#ef9aa3"/></linearGradient></defs><rect x="28" y="64" width="374" height="142" rx="70" fill="url(#vessel)" stroke="#fff" stroke-opacity=".55" stroke-width="3"/><rect x="42" y="87" width="346" height="96" rx="48" fill="#742332" opacity=".78"/><path d="M90 88C124 102 142 151 174 182H68C57 158 62 112 90 88Z" fill="#f6ce51"/><path d="M315 88C281 102 263 151 231 182h106c11-24 6-70-22-94Z" fill="#efb13f"/><path d="M174 182C199 160 221 148 244 154" fill="none" stroke="#fff" stroke-width="4" stroke-dasharray="7 7"/><circle cx="214" cy="135" r="20" fill="#ef4444" opacity=".92"/><text x="215" y="38" text-anchor="middle" fill="#fff" font-size="18" font-weight="800">Plaque burden + plaque behaviour</text><text x="215" y="239" text-anchor="middle" fill="#dff9ff" font-size="14">Fixed stenosis causes demand ischemia; disruption can trigger thrombosis</text></svg>`;
    if(type==="ecg") return `<svg viewBox="0 0 430 280"><rect x="20" y="25" width="390" height="230" rx="22" fill="rgba(255,255,255,.08)" stroke="rgba(255,255,255,.25)"/><path d="M36 143h62l14-31 19 69 22-105 28 134 21-67h37l12-26 18 52 17-26h109" fill="none" stroke="#a7f3d0" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/><g fill="#fff" font-size="13" font-weight="800"><text x="68" y="230">I</text><text x="117" y="230">II</text><text x="166" y="230">III</text><text x="214" y="230">aVR</text><text x="266" y="230">V1</text><text x="315" y="230">V4</text><text x="364" y="230">V6</text></g><text x="215" y="55" fill="#fff" text-anchor="middle" font-size="18" font-weight="850">ECG: anatomy written as voltage</text></svg>`;
    if(type==="acute") return `<svg viewBox="0 0 430 280"><circle cx="215" cy="138" r="94" fill="rgba(255,255,255,.08)" stroke="rgba(255,255,255,.28)" stroke-width="3"/><path d="M215 220C153 178 121 150 121 104c0-27 19-47 46-47 21 0 38 12 48 31 10-19 27-31 48-31 27 0 46 20 46 47 0 46-32 74-94 116Z" fill="#d65b68" opacity=".92" stroke="#fff" stroke-width="3"/><path d="M111 138h59l15-35 24 81 23-65 17 38h70" fill="none" stroke="#fff" stroke-width="5" stroke-linecap="round"/><circle cx="215" cy="137" r="126" fill="none" stroke="#f4d98c" stroke-width="3" stroke-dasharray="8 10"/><text x="215" y="25" text-anchor="middle" fill="#fff" font-weight="850" font-size="18">Time-sensitive ischemia</text></svg>`;
    if(type==="prevention") return `<svg viewBox="0 0 430 280"><circle cx="215" cy="137" r="105" fill="rgba(255,255,255,.08)" stroke="rgba(255,255,255,.25)"/><path d="M215 219C157 181 127 153 127 110c0-25 18-44 43-44 20 0 36 11 45 29 9-18 25-29 45-29 25 0 43 19 43 44 0 43-30 71-88 109Z" fill="#d85c68" stroke="#fff" stroke-width="3"/><path d="M215 38v29M215 207v29M116 137H87M343 137h-29M145 67l20 20M285 187l20 20M285 87l20-20M145 207l20-20" stroke="#a7f3d0" stroke-width="5" stroke-linecap="round"/><text x="215" y="260" text-anchor="middle" fill="#fff" font-size="16" font-weight="800">Prevent the next event</text></svg>`;
    return `<svg class="coronary-svg" viewBox="0 0 430 300"><defs><linearGradient id="heart" x1="0" x2="1"><stop stop-color="#c64b58"/><stop offset="1" stop-color="#8e3042"/></linearGradient></defs><path d="M214 264C132 210 88 170 88 105c0-39 28-68 66-68 29 0 52 17 60 44 10-27 32-44 61-44 39 0 67 29 67 68 0 65-44 105-128 159Z" fill="url(#heart)" stroke="#ffe7ea" stroke-width="3"/><path d="M215 80c-4 32-2 54-2 75M211 102c-35 12-53 32-65 64M214 118c30 11 53 35 68 73M211 151c-20 15-30 36-32 64M238 157c14 13 22 31 23 54" fill="none" stroke="#f5d36b" stroke-width="7" stroke-linecap="round"/><circle cx="146" cy="166" r="8" fill="#ef4444" stroke="#fff" stroke-width="2"/><text x="214" y="289" fill="#fff" text-anchor="middle" font-size="16" font-weight="800">Coronary blood flow must match myocardial work</text></svg>`;
  }

  const navGroups = [
    {title:"Start",items:[{id:"overview",label:"Learning map"},{id:"foundations",label:"Coronary foundations"},{id:"atherosclerosis",label:"Atherosclerosis"}]},
    {title:"Chronic ischemia",items:[{id:"stable-angina",label:"Stable angina"},{id:"investigations",label:"Diagnostic testing"},{id:"chronic-treatment",label:"Chronic treatment"},{id:"revascularization",label:"PCI vs CABG"},{id:"special-syndromes",label:"ANOCA, INOCA & MINOCA"}]},
    {title:"Acute ischemia",items:[{id:"acs-triage",label:"ACS triage"},{id:"stemi",label:"STEMI reperfusion"},{id:"nste-acs",label:"NSTEMI & unstable angina"},{id:"mi-localization",label:"MI types & ECG localization"},{id:"complications",label:"MI complications"},{id:"post-mi",label:"Post-MI prevention"}]},
    {title:"Practice",items:[{id:"clinical-lab",label:"Clinical reasoning lab"},{id:"flashcards",label:"Flashcards"},{id:"quiz",label:"Exam quiz"},{id:"sources",label:"Sources & scope"}]}
  ];

  const sources = [
    {id:"S1",title:"2024 ESC Guidelines for the management of chronic coronary syndromes",org:"European Society of Cardiology",url:"https://www.escardio.org/guidelines/clinical-practice-guidelines/all-esc-practice-guidelines/chronic-coronary-syndromes/"},
    {id:"S2",title:"2025 ACC/AHA/ACEP/NAEMSP/SCAI Guideline for Acute Coronary Syndromes",org:"American Heart Association / American College of Cardiology",url:"https://professional.heart.org/en/science-news/2025-guideline-for-the-management-of-patients-with-acute-coronary-syndromes"},
    {id:"S3",title:"2023 ESC Guidelines for the management of acute coronary syndromes",org:"European Society of Cardiology",url:"https://www.escardio.org/guidelines/clinical-practice-guidelines/all-esc-practice-guidelines/acute-coronary-syndromes/"},
    {id:"S4",title:"2023 AHA/ACC Multisociety Guideline for Chronic Coronary Disease",org:"American College of Cardiology",url:"https://www.acc.org/guidelines/hubs/chronic-coronary-disease"},
    {id:"S5",title:"Uploaded reconstructed Ischemic Heart Disease chapter",org:"Local study source",url:"assets/ischemic-heart-disease-source.pdf"}
  ];

  const modules = {};

  modules.overview = {
    title:"Learning map",
    search:"ischemic heart disease overview chronic coronary syndrome ACS myocardial infarction roadmap",
    render:()=>`${hero({eyebrow:"Cardiology · Chapter 5",title:"Ischemic Heart Disease",intro:"A connected, physiology-first course from coronary anatomy and atherosclerosis to chronic angina, acute coronary syndromes, myocardial infarction, complications, and secondary prevention.",chips:["18 linked modules","Interactive clinical tools","ECG localization","Flip flashcards","Case-based quiz"],visual:"coronary"})}
      ${tts("The master clinical sequence",`<div class="flow-row"><div class="flow-step">Recognize ischemic symptoms</div><div class="flow-step">Separate stable from acute</div><div class="flow-step">Use ECG + troponin correctly</div><div class="flow-step">Define anatomy or physiology</div><div class="flow-step">Relieve ischemia</div><div class="flow-step">Prevent death and recurrence</div></div>${callout("danger","Emergency branch","New, rest, crescendo, prolonged, or recurrent chest pressure—especially with dyspnea, diaphoresis, syncope, shock, or ischemic ECG changes—belongs on an acute coronary syndrome pathway, not an outpatient stable-angina pathway.")}`)}
      ${tts("Course architecture",`<div class="grid grid-3">${card("1 · Foundations","Coronary territories, dominance, oxygen supply–demand balance, and the clinical spectrum.","blue")}${card("2 · Chronic coronary syndromes","Symptom pattern, clinical likelihood, CCTA or functional imaging, antianginal therapy, and event prevention.","accent")}${card("3 · Acute coronary syndromes","Rapid ECG, serial high-sensitivity troponin, antithrombotic therapy, reperfusion, invasive strategy, and complication recognition.","danger")}${card("4 · Special phenotypes","Vasospasm, microvascular dysfunction, ANOCA/INOCA, MINOCA, silent ischemia, and type 2 MI.","warn")}${card("5 · Bedside-to-ECG integration","Inferior plus right-sided leads, posterior leads, reciprocal changes, shock patterns, and mechanical complications.","blue")}${card("6 · Active recall","Clinical reasoning tools, true flip cards, keyboard control, and an exam-oriented quiz with explanations.","accent")}</div><div class="route-links">${routeButton("foundations","Start with coronary physiology")}${routeButton("stable-angina","Go to chronic angina")}${routeButton("acs-triage","Go to ACS triage")}${routeButton("clinical-lab","Open clinical lab")}</div>`)}
      ${tts("How to use the lab",`<div class="grid grid-4"><div class="mini-stat card"><strong>⌕</strong><div><b>Search</b><br><span class="muted">Press / and search any term.</span></div></div><div class="mini-stat card"><strong>★</strong><div><b>Bookmark</b><br><span class="muted">Save individual teaching blocks.</span></div></div><div class="mini-stat card"><strong>▶</strong><div><b>Listen</b><br><span class="muted">Use speech controls on each block.</span></div></div><div class="mini-stat card"><strong>✓</strong><div><b>Track</b><br><span class="muted">Visited modules persist locally.</span></div></div></div>`)}
    `
  };

  modules.foundations = {
    title:"Coronary foundations",
    search:"coronary anatomy LAD LCx RCA dominance oxygen supply demand tachycardia diastole",
    render:()=>`${hero({eyebrow:"Module 1",title:"Coronary Foundations",intro:"Before memorizing syndromes, understand which artery supplies which territory and why ischemia appears when oxygen supply cannot meet myocardial demand.",chips:["LAD · LCx · RCA","Coronary dominance","Diastolic perfusion","Supply–demand balance"],visual:"coronary"})}
      ${tts("Coronary anatomy that changes clinical reasoning",`${table(["Vessel","Major branches","Principal territory","High-yield consequence"],[
        ["Left main","LAD + LCx","Most of LV, left atrium, anterior two-thirds of septum","Critical disease threatens a large myocardial territory."],
        ["LAD","Diagonal + septal","Anterior wall, apex, anterior septum","Large anterior MI can produce pump failure, septal complications, and ventricular arrhythmia."],
        ["LCx","Obtuse marginal; sometimes PDA","Lateral/posterolateral LV; variable posterior or inferior territory","Posterior or lateral ischemia may be electrically subtle on a standard ECG."],
        ["RCA","Acute marginal, nodal branches, usually PDA","RV, inferior LV, posterior septum, often SA/AV nodes","Inferior MI may bring bradycardia, AV block, or RV infarction."]
      ])}${callout("","Dominance","Coronary dominance is defined by the artery giving rise to the posterior descending artery. It changes the expected infarct territory and conduction-system involvement.")}`)}
      ${tts("Oxygen supply versus oxygen demand",`<div class="grid grid-2">${card("Supply falls with","<ul class=\"key-list\"><li>Fixed or dynamic epicardial narrowing</li><li>Reduced diastolic perfusion pressure</li><li>Anemia or hypoxemia</li><li>Microvascular dysfunction</li><li>Shortened diastolic perfusion time</li></ul>","blue")}${card("Demand rises with","<ul class=\"key-list\"><li>Tachycardia</li><li>Hypertension and wall stress</li><li>Increased contractility</li><li>LV hypertrophy</li><li>Fever, thyrotoxicosis, or severe exertion</li></ul>","danger")}</div>${callout("warn","Why tachycardia is especially harmful","It increases myocardial work while shortening diastole—the phase in which most left-coronary perfusion occurs. It therefore worsens both sides of the equation at once.")}`)}
      ${tts("Interactive supply–demand lab",`<div class="interactive-panel" id="supply-demand-lab"><div class="control-row"><label for="hr-range"><b>Heart rate</b></label><input id="hr-range" type="range" min="50" max="150" value="75"><output id="hr-output">75 bpm</output></div><div class="control-row"><label for="stenosis-range"><b>Flow limitation</b></label><input id="stenosis-range" type="range" min="0" max="100" value="25"><output id="stenosis-output">25%</output></div><div class="control-row"><label for="hb-range"><b>Hemoglobin</b></label><input id="hb-range" type="range" min="6" max="16" step="0.5" value="13"><output id="hb-output">13 g/dL</output></div><div class="control-row"><label for="sbp-range"><b>Systolic pressure</b></label><input id="sbp-range" type="range" min="80" max="210" value="125"><output id="sbp-output">125 mmHg</output></div><div class="result-box"><span class="pill blue">Teaching model, not a clinical calculator</span><div class="metric" id="ischemia-index">Low mismatch</div><p id="ischemia-explanation" class="muted">Supply is adequate for the selected demand.</p></div></div>`)}
      ${tts("Clinical spectrum",`<div class="flow-row"><div class="flow-step">Silent ischemia</div><div class="flow-step">Chronic angina</div><div class="flow-step">Unstable angina</div><div class="flow-step">NSTEMI</div><div class="flow-step">STEMI</div><div class="flow-step">HF · arrhythmia · sudden death</div></div><div class="route-links">${routeButton("atherosclerosis","Why plaques form")}${routeButton("mi-localization","Map arteries to ECG leads")}</div>`)}
    `
  };

  modules.atherosclerosis = {
    title:"Atherosclerosis",
    search:"atherosclerosis endothelial dysfunction LDL plaque rupture erosion thrombosis risk factors",
    render:()=>`${hero({eyebrow:"Module 2",title:"Atherosclerosis & Coronary Thrombosis",intro:"Atherosclerosis is a chronic inflammatory arterial disease. Clinical events depend not only on how narrow a plaque is, but also on whether its surface disrupts and triggers thrombosis.",chips:["LDL retention","Inflammation","Stable plaque","Plaque rupture or erosion","Thrombosis"],visual:"plaque"})}
      ${tts("From risk factor to coronary event",`<div class="flow-row"><div class="flow-step">Endothelial dysfunction</div><div class="flow-step">LDL retention and modification</div><div class="flow-step">Monocyte recruitment</div><div class="flow-step">Foam cells and fatty streak</div><div class="flow-step">Fibrous plaque</div><div class="flow-step">Rupture or erosion → thrombus</div></div><p class="muted">Smooth-muscle migration, extracellular matrix production, calcification, inflammation, and necrotic-core formation determine plaque structure and behaviour.</p>`)}
      ${tts("Risk-factor architecture",`<div class="grid grid-2">${card("Non-modifiable context","<ul class=\"key-list\"><li>Increasing age</li><li>Family history or inherited lipid disorder</li><li>Genetic susceptibility</li><li>Lifetime hormonal and biological factors</li><li>Established vascular disease</li></ul>","blue")}${card("Modifiable or treatable drivers","<ul class=\"key-list\"><li>Atherogenic lipoproteins, especially LDL cholesterol</li><li>Smoking and tobacco exposure</li><li>Hypertension</li><li>Diabetes and insulin resistance</li><li>Obesity, inactivity, unhealthy diet, and psychosocial stress</li><li>Chronic kidney disease and inflammatory disease</li></ul>","accent")}</div>`)}
      ${tts("Stable plaque versus vulnerable plaque",`${table(["Feature","Stable fibrotic plaque","Vulnerable plaque with disruption"],[
        ["Typical effect","Predictable demand ischemia as flow reserve becomes inadequate","Abrupt platelet activation and thrombin generation"],
        ["Surface","Relatively intact fibrous cap","Rupture or erosion exposes thrombogenic material"],
        ["Flow pattern","Often fixed limitation","Intermittent, subtotal, or fully occlusive thrombus"],
        ["Clinical expression","Chronic coronary syndrome","Unstable angina, NSTEMI, STEMI, sudden death"]
      ])}${callout("warn","Important correction","Routine antimicrobial treatment is not justified by older hypotheses involving organisms such as Chlamydia or Helicobacter. Prevention targets established atherosclerotic risk factors.")}`)}
      ${tts("Clickable plaque progression",`<div class="interactive-panel"><div class="tabs" id="plaque-tabs"><button class="tab-button active" data-plaque="0">Endothelium</button><button class="tab-button" data-plaque="1">Fatty streak</button><button class="tab-button" data-plaque="2">Fibrous plaque</button><button class="tab-button" data-plaque="3">Disruption</button><button class="tab-button" data-plaque="4">Thrombosis</button></div><div class="result-box" id="plaque-detail"><h3>Endothelial dysfunction</h3><p>Hypertension, smoking, diabetes, and atherogenic lipoproteins alter endothelial signalling and permeability, creating a surface that retains lipoproteins and recruits inflammatory cells.</p></div></div><div class="route-links">${routeButton("stable-angina","See fixed-plaque ischemia")}${routeButton("acs-triage","See plaque disruption in ACS")}</div>`)}
    `
  };

  modules["stable-angina"] = {
    title:"Stable angina",
    search:"chronic coronary syndrome stable angina chest pain typical angina CCS grading Levine sign anginal equivalent",
    render:()=>`${hero({eyebrow:"Module 3",title:"Chronic Coronary Syndromes & Stable Angina",intro:"Recognize a reproducible ischemic pattern, identify features that make it unstable, and remember that breathlessness or fatigue may replace classic chest pain.",chips:["Predictable threshold","Several minutes","Rest or nitrate relief","Anginal equivalents","CCS class I–IV"],visual:"coronary"})}
      ${tts("The typical ischemic symptom pattern",`${table(["Feature","Typical ischemic description","Features suggesting another cause"],[
        ["Site","Retrosternal pressure or diffuse discomfort","Focal pain reproducible with one fingertip"],
        ["Character","Pressure, heaviness, tightness, squeezing, burning, or breathlessness","Sharp pleuritic pain or pain strongly altered by movement"],
        ["Radiation","Arm, shoulder, neck, jaw, back, or epigastrium","Isolated very brief localized pain"],
        ["Trigger","Exertion, emotion, cold, or heavy meal","Random seconds-long episodes"],
        ["Relief","Rest or short-acting nitrate, usually within minutes","Persistent pain for hours without objective ischemia"],
        ["Duration","Usually several minutes; stable episodes are generally under 15–20 minutes","Instantaneous pain or continuous pain over many hours"]
      ])}${callout("","Do not overuse Levine sign","A clenched fist over the sternum can support the history but is neither sensitive nor specific enough to diagnose coronary disease.")}`)}
      ${tts("Anginal equivalents and silent ischemia",`<div class="grid grid-3">${card("Anginal equivalents","Exertional dyspnea, unusual fatigue, nausea, diaphoresis, or epigastric discomfort may replace chest pain.","blue")}${card("Who may present atypically","Older adults, people with diabetes, women, patients with CKD, and transplant recipients may have little or no pain.","warn")}${card("Silent ischemia","Objective ischemia without recognized symptoms, detected during monitoring or provocative testing.","accent")}</div>`)}
      ${tts("Interactive chest-pain pattern check",`<div class="interactive-panel" id="angina-checker"><p><b>Select the three classic descriptors that apply.</b></p><div class="choice-grid"><button class="choice-button" data-angina-criterion="retrosternal">Retrosternal discomfort with a pressure-like quality</button><button class="choice-button" data-angina-criterion="trigger">Provoked by exertion or emotional stress</button><button class="choice-button" data-angina-criterion="relief">Relieved by rest or nitrate within minutes</button></div><div class="result-box"><div class="metric" id="angina-label">0 of 3 criteria</div><p id="angina-note" class="muted">This historical classification describes symptom typicality; it does not diagnose or exclude coronary disease.</p></div></div>`)}
      ${tts("Canadian Cardiovascular Society functional class",`${table(["Class","Functional limitation"],[
        ["I","Ordinary activity does not cause angina; symptoms occur only with strenuous, rapid, or prolonged exertion."],
        ["II","Slight limitation: rapid walking, hills, stairs after meals, cold, wind, or emotional stress."],
        ["III","Marked limitation: symptoms with less-than-ordinary activity, such as one to two blocks or one flight of stairs."],
        ["IV","Symptoms with minimal activity or at rest."]
      ])}${callout("danger","Unstable features override the stable label","New or crescendo symptoms, pain at rest, prolonged episodes, hemodynamic compromise, or ischemic ECG changes require urgent ACS assessment.")}`)}
      ${tts("High-yield differentials",`<div class="grid grid-3">${card("Immediately dangerous","Aortic syndrome, pulmonary embolism, tension pneumothorax, esophageal rupture, pericardial tamponade, and ACS.","danger")}${card("Common cardiac mimics","Pericarditis, myocarditis, aortic stenosis, hypertrophic cardiomyopathy, tachyarrhythmia, and heart failure.","blue")}${card("Common non-cardiac mimics","Gastroesophageal disease, musculoskeletal pain, anxiety/panic, respiratory infection, pleurisy, and radicular pain.","warn")}</div><div class="route-links">${routeButton("investigations","Choose the next diagnostic test")}${routeButton("acs-triage","Review the acute branch")}</div>`)}
    `
  };

  modules.investigations = {
    title:"Diagnostic testing",
    search:"stable angina diagnostic approach clinical likelihood ECG echocardiography CCTA stress imaging FFR iFR troponin",
    render:()=>`${hero({eyebrow:"Module 4",title:"Testing Suspected Chronic Coronary Disease",intro:"The correct test depends on the clinical question: exclude acute injury, assess ventricular function, define coronary anatomy, demonstrate inducible ischemia, or determine whether a lesion is physiologically significant.",chips:["Clinical likelihood","Resting ECG","Echocardiography","CCTA","Stress imaging","FFR / iFR"],visual:"ecg"})}
      ${tts("Stepwise diagnostic approach",`<div class="flow-row"><div class="flow-step">Exclude ACS and dangerous alternatives</div><div class="flow-step">Estimate clinical likelihood</div><div class="flow-step">Resting ECG + basic labs + echo</div><div class="flow-step">CCTA or functional imaging</div><div class="flow-step">Define risk and anatomy</div><div class="flow-step">Treat symptoms and prevent events</div></div><ol><li>Identify instability before outpatient testing.</li><li>Assess risk factors, baseline ECG, hemoglobin, renal function, glucose/HbA1c, and lipid profile.</li><li>Use resting echocardiography to assess ventricular function and structural alternatives.</li><li>Select anatomical or functional testing according to likelihood, patient factors, local expertise, and the decision the result will change.</li><li>Use invasive angiography for severe symptoms despite therapy, high event risk, inconclusive non-invasive testing, or anticipated revascularization.</li></ol>`)}
      ${tts("What each test contributes",`${table(["Test","Best contribution","Important limitation"],[
        ["Resting ECG","Prior infarction, conduction disease, baseline ST–T abnormality, or active ischemia","May be normal between attacks."],
        ["High-sensitivity troponin","Rules in or rules out acute myocardial injury when ACS is suspected","Not a screening test for stable angina; elevation requires context."],
        ["Echocardiography","LV function, regional wall motion, valves, and alternative structural diagnoses","A normal resting study does not exclude inducible ischemia."],
        ["Coronary CT angiography","Defines anatomy and can effectively exclude obstructive CAD in suitable patients","Heavy calcification, fast rhythm, renal dysfunction, or contrast allergy may limit quality or safety."],
        ["Stress imaging","Demonstrates inducible ischemia and supports risk stratification","Accuracy and suitability depend on modality and patient factors."],
        ["Exercise ECG","Functional capacity, symptoms, heart-rate response, and exercise-induced ECG change","Lower accuracy with an abnormal baseline ECG; not the universal first test."],
        ["Invasive angiography + FFR/iFR","Definitive anatomy and lesion-specific physiological significance","Invasive; should answer a clear diagnostic or therapeutic question."]
      ])}${callout("warn","Current practice point","A normal exercise ECG alone does not exclude coronary disease. Contemporary pathways often favor CCTA or stress imaging in appropriate patients.")}`)}
      ${tts("Interactive test selector",`<div class="interactive-panel" id="test-selector"><p><b>What is your main clinical question?</b></p><div class="choice-grid"><button class="choice-button" data-test-choice="acute">Is there acute myocardial injury right now?</button><button class="choice-button" data-test-choice="function">What is LV function and is there structural disease?</button><button class="choice-button" data-test-choice="anatomy">Can I define or exclude obstructive coronary anatomy non-invasively?</button><button class="choice-button" data-test-choice="ischemia">Is there inducible ischemia and what is the risk?</button><button class="choice-button" data-test-choice="lesion">Is a specific angiographic lesion flow-limiting?</button></div><div class="result-box" id="test-result"><h3>Select a clinical question</h3><p class="muted">The output will identify the most directly informative test family and its limitation.</p></div></div>`)}
      ${tts("Interpret a test in context",`<div class="grid grid-3">${card("Normal does not always mean absent","A resting ECG and resting echo may both be normal despite inducible ischemia.","blue")}${card("Abnormal does not always mean ACS","Troponin indicates myocardial injury; sepsis, tachyarrhythmia, pulmonary embolism, myocarditis, and heart failure can elevate it.","warn")}${card("Anatomy is not physiology","An intermediate stenosis may need FFR or iFR to determine whether it limits flow.","accent")}</div><div class="route-links">${routeButton("chronic-treatment","Build the treatment plan")}${routeButton("revascularization","Decide when anatomy changes therapy")}</div>`)}
    `
  };

  modules["chronic-treatment"] = {
    title:"Chronic treatment",
    search:"chronic coronary disease treatment statin antiplatelet ACE inhibitor beta blocker calcium channel blocker nitrate ranolazine lifestyle rehabilitation",
    render:()=>`${hero({eyebrow:"Module 5",title:"Chronic Coronary Disease Treatment",intro:"Always separate two goals: reduce future cardiovascular events and relieve present ischemic symptoms. The drugs that improve symptoms are not automatically the same interventions that improve prognosis.",chips:["Event prevention","Symptom relief","Risk-factor control","Cardiac rehabilitation","Shared decisions"],visual:"prevention"})}
      ${tts("A · Event prevention",`${table(["Intervention","Purpose"],[
        ["Smoking cessation and lifestyle therapy","Reduce recurrent events and improve functional capacity."],
        ["High-intensity or maximally tolerated statin","Lower LDL cholesterol and plaque-related risk; add non-statin therapy when thresholds or targets are not reached."],
        ["Antiplatelet therapy","Single antiplatelet therapy is usual in established obstructive CAD unless recent ACS/PCI or another indication requires dual therapy."],
        ["Blood-pressure and diabetes control","Reduce cardiovascular and microvascular complications."],
        ["ACE inhibitor or ARB when indicated","Particularly useful with hypertension, diabetes, CKD, LV dysfunction, or another compelling indication."],
        ["Cardiac rehabilitation and exercise prescription","Improve symptoms, adherence, risk factors, and quality of life."]
      ])}`)}
      ${tts("B · Symptom relief",`${table(["Drug class","Role","Key cautions"],[
        ["Short-acting nitrate","Immediate relief or prophylaxis before exertion","Hypotension; never combine with PDE-5 inhibitors. Persistent pain needs urgent assessment."],
        ["Beta-blocker","Useful when heart-rate reduction is desirable; especially with prior MI, LV dysfunction, hypertension, or arrhythmia","Bradycardia, AV block, bronchospasm; avoid abrupt withdrawal."],
        ["Calcium-channel blocker","Alternative or add-on; central in vasospasm","Non-dihydropyridines may cause bradycardia or worsen reduced-EF HF; dihydropyridines may cause edema."],
        ["Long-acting nitrate","Add-on for persistent symptoms","Headache, hypotension, tolerance; provide a nitrate-free interval."],
        ["Ranolazine","Add-on when symptoms persist or BP/HR limit other drugs","QT prolongation and drug interactions."],
        ["Ivabradine or nicorandil","Selected add-on options depending on rhythm, LV function, region, and guideline context","Not universal first-line therapy; contraindications and interactions matter."]
      ])}${callout("warn","Beta-blocker nuance","Beta-blockers relieve angina, but long-term outcome benefit is not assumed for every patient with chronic coronary disease. The prognostic indication is strongest when another reason exists, such as recent MI or reduced LVEF.")}`)}
      ${tts("Interactive medication safety lab",`<div class="interactive-panel" id="drug-lab"><p><b>Select the scenario, then inspect the most important caution.</b></p><div class="tabs"><button class="tab-button active" data-drug-case="pde5">Recent PDE-5 inhibitor</button><button class="tab-button" data-drug-case="brady">HR 46 + AV block</button><button class="tab-button" data-drug-case="hfrEF">Reduced-EF heart failure</button><button class="tab-button" data-drug-case="vasospasm">Active vasospasm</button><button class="tab-button" data-drug-case="qt">Long QT / interactions</button></div><div class="result-box" id="drug-result"><h3>Avoid nitrate co-administration</h3><p>Combining nitrates with a recent phosphodiesterase-5 inhibitor can cause profound hypotension.</p></div></div>`)}
      ${tts("A practical two-column prescription",`<div class="grid grid-2">${card("Prevent events","Lifestyle + smoking cessation, lipid lowering, antithrombotic strategy, BP/diabetes control, rehabilitation, adherence, and vaccination where appropriate.","accent")}${card("Control symptoms","Choose antianginal therapy according to heart rate, blood pressure, LV function, rhythm, comorbidities, vasospasm, and patient tolerance.","blue")}</div><div class="route-links">${routeButton("revascularization","When medication is not enough")}${routeButton("special-syndromes","Tailor treatment to non-obstructive syndromes")}</div>`)}
    `
  };

  modules.revascularization = {
    title:"PCI vs CABG",
    search:"revascularization PCI CABG left main multivessel diabetes anatomy SYNTAX heart team",
    render:()=>`${hero({eyebrow:"Module 6",title:"Revascularization: PCI or CABG?",intro:"Revascularization can improve symptoms when guideline-directed therapy is insufficient and can improve prognosis in selected high-risk anatomy or ventricular dysfunction. The decision is anatomical, physiological, clinical, and preference-sensitive.",chips:["Symptom relief","High-risk anatomy","Diabetes","LV function","Heart Team"],visual:"coronary"})}
      ${tts("The decision frame",`<div class="grid grid-4">${card("Anatomy","Left main disease, number of vessels, lesion location, complexity, calcification, and expected completeness.","blue")}${card("Physiology","Ischemic burden and lesion significance, including FFR/iFR when appropriate.","accent")}${card("Patient factors","Diabetes, LV function, frailty, renal function, bleeding risk, surgical risk, and comorbidity.","warn")}${card("Values and logistics","Recovery time, durability, need for concomitant surgery, local expertise, and informed patient preference.","danger")}</div>`)}
      ${tts("Patterns that tend to favor each strategy",`${table(["PCI tends to be favored when","CABG tends to be favored when"],[
        ["Focal, technically suitable disease with a need for symptom relief","Left main or complex multivessel disease in a suitable surgical candidate"],
        ["Lower anatomic complexity","Diabetes with extensive multivessel disease when durable complete revascularization is expected"],
        ["High surgical risk or preference for a less invasive approach","Grafting offers better completeness or durability"],
        ["Rapid recovery is important and expected outcomes are comparable","Concomitant cardiac surgery is required"]
      ])}${callout("","Avoid the old vessel-count shortcut","Do not reduce the choice to ‘PCI for one or two vessels, CABG for three.’ Integrate anatomy, complexity, diabetes, ventricular function, surgical risk, completeness, and patient preference.")}`)}
      ${tts("Interactive Heart Team board",`<div class="interactive-panel" id="revasc-lab"><div class="choice-grid"><button class="choice-button" data-revasc="focal">Focal technically suitable lesion, lower complexity, high surgical risk</button><button class="choice-button" data-revasc="diabetes">Diabetes with extensive complex multivessel disease</button><button class="choice-button" data-revasc="leftmain">Left main disease with complex anatomy</button><button class="choice-button" data-revasc="symptoms">Persistent angina despite optimized medical therapy, anatomy not yet defined</button><button class="choice-button" data-revasc="surgery">Coronary disease plus another valve operation already required</button></div><div class="result-box" id="revasc-result"><h3>Select a scenario</h3><p class="muted">The result states the direction of preference and the missing information that still matters.</p></div></div>`)}
      ${tts("When not to rush to a procedure",`<ul class="check-list"><li>Symptoms are controlled and no prognostic anatomy or large ischemic burden has been identified.</li><li>The lesion is angiographically intermediate and physiological significance is unknown.</li><li>The procedural risk outweighs likely symptom or prognostic benefit.</li><li>The patient has not received a clear explanation of medical therapy, PCI, CABG, and expected trade-offs.</li></ul><div class="route-links">${routeButton("chronic-treatment","Return to medical therapy")}${routeButton("acs-triage","See revascularization in acute ACS")}</div>`)}
    `
  };

  modules["special-syndromes"] = {
    title:"ANOCA, INOCA & MINOCA",
    search:"vasospastic Prinzmetal microvascular angina ANOCA INOCA MINOCA non obstructive coronary arteries",
    render:()=>`${hero({eyebrow:"Module 7",title:"Vasospasm, Microvascular Ischemia & Non-Obstructive Syndromes",intro:"A non-obstructive angiogram does not make ischemic symptoms imaginary or harmless. The next step is to identify the mechanism: epicardial spasm, microvascular dysfunction, plaque disruption, embolism, dissection, myocarditis, Takotsubo syndrome, or another cause.",chips:["Vasospastic angina","Microvascular angina","ANOCA / INOCA","MINOCA"],visual:"plaque"})}
      ${tts("Syndrome comparison",`${table(["Syndrome","Typical clue","Diagnostic or treatment principle"],[
        ["Vasospastic (Prinzmetal) angina","Rest pain, often nocturnal, with transient ST elevation or depression during spasm","Calcium-channel blockers and nitrates are central; avoid non-selective beta-blockers when vasospasm is active."],
        ["Microvascular angina","Angina or ischemia without a flow-limiting epicardial stenosis","Assess coronary microvascular dysfunction; tailor antianginal and risk-factor therapy."],
        ["ANOCA / INOCA","Angina or ischemia with non-obstructive coronary arteries","Do not dismiss symptoms; consider spasm, microvascular dysfunction, myocardial bridging, and alternatives."],
        ["MINOCA","Clinical MI with no obstructive lesion sufficient to explain it","A working diagnosis requiring evaluation for plaque disruption, spasm, embolism, spontaneous dissection, myocarditis, Takotsubo syndrome, and other causes."]
      ])}`)}
      ${tts("Interactive mechanism sorter",`<div class="interactive-panel" id="special-sorter"><div class="choice-grid"><button class="choice-button" data-special="spasm">Nocturnal rest pain with transient ST elevation that resolves</button><button class="choice-button" data-special="micro">Exertional angina + ischemia, but no flow-limiting epicardial stenosis</button><button class="choice-button" data-special="minoca">Troponin rise/fall + ischemic evidence, angiography without an explanatory obstructive lesion</button><button class="choice-button" data-special="dismiss">Normal-looking epicardial arteries, therefore symptoms are non-cardiac</button></div><div class="result-box" id="special-result"><h3>Select a presentation</h3><p class="muted">Non-obstructive coronary anatomy is a starting point for mechanism-based evaluation, not a final dismissal.</p></div></div>`)}
      ${tts("Three conceptual traps",`<div class="grid grid-3">${card("Trap 1 · Angiography is not the whole coronary circulation","Epicardial anatomy may look non-obstructive while the microcirculation is dysfunctional.","warn")}${card("Trap 2 · MINOCA is not one disease","It is a working diagnosis. Cardiac MRI, intracoronary imaging, and targeted functional testing may clarify the mechanism.","danger")}${card("Trap 3 · Spasm changes drug choice","Calcium-channel blockers and nitrates are central; non-selective beta-blockade may worsen active vasospasm.","blue")}</div><div class="route-links">${routeButton("acs-triage","Apply the ACS definition")}${routeButton("mi-localization","Distinguish type 1, type 2, and non-ischemic injury")}</div>`)}
    `
  };

  modules["acs-triage"] = {
    title:"ACS triage",
    search:"acute coronary syndrome triage ECG aspirin high sensitivity troponin oxygen unstable angina NSTEMI STEMI emergency",
    render:()=>`${hero({eyebrow:"Module 8",title:"Acute Coronary Syndrome Triage",intro:"ACS is a time-sensitive spectrum: unstable angina, NSTEMI, and STEMI. Start with physiology and ECG, then use serial high-sensitivity troponin and risk assessment without delaying reperfusion for an established acute occlusion.",chips:["12-lead ECG","Serial hs-cTn","Aspirin","Monitoring","Reperfusion or invasive strategy"],visual:"acute"})}
      ${tts("Definitions that prevent confusion",`${table(["Condition","ECG pattern","Cardiac troponin","Core implication"],[
        ["Unstable angina","No persistent ST elevation; may show transient ST depression or T-wave change","No acute rise/fall above the assay-specific 99th percentile","Ischemia without biomarker-defined necrosis; less common in the hs-troponin era."],
        ["NSTEMI","No persistent ST elevation; ST depression, T-wave inversion, or even a normal ECG","Acute rise/fall with at least one value above the 99th percentile plus evidence of ischemia","MI requiring antithrombotic therapy and risk-based invasive management."],
        ["STEMI / acute occlusion pattern","Persistent ST elevation or an equivalent occlusion pattern in the correct clinical setting","Troponin usually rises, but reperfusion must not wait","Immediate reperfusion strategy."]
      ])}`)}
      ${tts("Immediate assessment",`<div class="flow-row"><div class="flow-step">Recognize symptoms</div><div class="flow-step">ABC, saturation, BP, perfusion</div><div class="flow-step">12-lead ECG rapidly</div><div class="flow-step">Monitor + IV access</div><div class="flow-step">Aspirin if appropriate</div><div class="flow-step">hs-cTn pathway</div><div class="flow-step">Choose reperfusion or invasive strategy</div></div><ol><li>Assess rhythm, heart failure, and shock while obtaining the first ECG.</li><li>Repeat the ECG if symptoms persist or the first tracing is non-diagnostic.</li><li>Use an assay-specific rapid hs-cTn algorithm when appropriate.</li><li>Add P2Y12 inhibition and anticoagulation according to the ACS and reperfusion strategy.</li><li>Use oxygen for hypoxemia or respiratory distress—not routinely for normal saturation.</li><li>Treat pain and complications without creating delays to reperfusion.</li></ol>${callout("danger","Emergency warning","Persistent or recurrent chest pressure, dyspnea, syncope, diaphoresis, shock, or an ischemic ECG is an emergency. Nitrate response neither proves nor excludes ACS.")}`)}
      ${tts("Interactive first-ten-minutes sequence",`<div class="interactive-panel" id="acs-sequence"><p><b>Click the actions in the safest clinical order.</b></p><div class="choice-grid" id="acs-sequence-choices"><button class="choice-button" data-seq="ecg">Obtain and interpret a 12-lead ECG</button><button class="choice-button" data-seq="abc">Assess ABC, perfusion, saturation, rhythm, HF, and shock</button><button class="choice-button" data-seq="troponin">Obtain hs-cTn and plan serial sampling</button><button class="choice-button" data-seq="aspirin">Give chewable aspirin if not contraindicated</button><button class="choice-button" data-seq="strategy">Activate reperfusion or invasive pathway according to ECG and risk</button></div><div class="result-box"><div class="metric" id="acs-sequence-score">0 / 5</div><p id="acs-sequence-note" class="muted">Start with physiological stability, but obtain the ECG in parallel as early as possible.</p><button class="secondary-button" id="reset-acs-sequence" type="button">Reset sequence</button></div></div>`)}
      ${tts("High-sensitivity troponin interpretation",`${table(["Pattern","Interpretation"],[
        ["Low value with no significant change in a validated rapid pathway","May support rule-out when symptom timing and clinical risk are appropriate."],
        ["Rise and/or fall with ischemic symptoms or ECG/imaging evidence","Supports acute MI."],
        ["Stable chronic elevation","Consider CKD, structural heart disease, or chronic myocardial injury rather than automatically diagnosing ACS."],
        ["Acute elevation without evidence of ischemia","Acute myocardial injury; investigate sepsis, tachyarrhythmia, PE, myocarditis, HF, and other causes."],
        ["Recurrent symptoms soon after MI","Interpret serial change and clinical context; a persistently elevated troponin can complicate diagnosis."]
      ])}${callout("warn","No universal troponin number","Do not memorize one cutoff such as 0.04 ng/mL or 14 ng/L as a universal MI threshold. Use the local assay's validated 99th percentile and serial change.")}`)}
      ${tts("Supportive and antithrombotic principles",`${table(["Therapy","Modern principle"],[
        ["Aspirin","Loading dose followed by maintenance unless contraindicated."],
        ["P2Y12 inhibitor","Choice and timing depend on ACS type, PCI plan, bleeding risk, age, prior stroke, and local protocol."],
        ["Anticoagulant","Used in the acute phase; agent depends on the invasive strategy and renal function."],
        ["Nitrates","Relieve ischemic discomfort and hypertension when BP allows; avoid in hypotension, RV infarction, or recent PDE-5 inhibitor use."],
        ["Morphine","Not routine; reserve for severe refractory pain because of hypotension and delayed oral antiplatelet absorption."],
        ["Beta-blocker","Use selectively when stable; avoid in shock, acute HF, severe bradycardia, or high-grade block."],
        ["High-intensity statin","Initiate early and intensify according to LDL response and recurrent risk."]
      ])}<div class="route-links">${routeButton("stemi","Open STEMI pathway")}${routeButton("nste-acs","Open NSTE-ACS pathway")}</div>`)}
    `
  };

  modules.stemi = {
    title:"STEMI reperfusion",
    search:"STEMI primary PCI fibrinolysis reperfusion rescue PCI 12 hours radial access cardiogenic shock",
    render:()=>`${hero({eyebrow:"Module 9",title:"STEMI: Reperfusion Cannot Wait",intro:"When the ECG and clinical setting establish an acute coronary occlusion, organize reperfusion immediately. Troponin supports diagnosis later; it must not become a reason for delay.",chips:["Primary PCI","Fibrinolysis","Rescue PCI","Radial access","Shock"],visual:"ecg"})}
      ${tts("Reperfusion strategies",`${table(["Strategy","When","Key points"],[
        ["Primary PCI","Preferred when it can be delivered promptly within a guideline-defined system by an experienced team","Treat the culprit lesion urgently; radial access is preferred when feasible; shock requires immediate revascularization planning."],
        ["Fibrinolysis","Selected patients, generally within 12 hours of symptom onset, when timely PCI is not achievable and no contraindication exists","Give immediately with antithrombotic therapy, transfer to a PCI-capable center, and perform rescue PCI if reperfusion fails."],
        ["No immediate reperfusion","Late presentation without ongoing ischemia or when risks clearly exceed benefit","Continue comprehensive ACS care and evaluate anatomy and complications as indicated."]
      ])}${callout("danger","Time-critical principle","Do not wait for troponin confirmation when the ECG and presentation establish STEMI or an equivalent acute coronary occlusion.")}`)}
      ${tts("Interactive reperfusion decision",`<div class="interactive-panel" id="stemi-lab"><div class="control-row"><label for="onset-range"><b>Hours since symptom onset</b></label><input id="onset-range" type="range" min="1" max="24" value="4"><output id="onset-output">4 h</output></div><div class="control-row"><label for="pci-range"><b>Estimated PCI delay</b></label><input id="pci-range" type="range" min="20" max="240" step="10" value="70"><output id="pci-output">70 min</output></div><label class="choice-button"><input id="lysis-contra" type="checkbox"> Major contraindication to fibrinolysis is present</label><label class="choice-button"><input id="ongoing-ischemia" type="checkbox" checked> Ongoing ischemia / acute occlusion pattern</label><div class="result-box" id="stemi-result"><h3>Primary PCI pathway</h3><p>Prompt PCI is available and is generally preferred. Activate the reperfusion system immediately.</p></div></div>`)}
      ${tts("How to judge reperfusion after fibrinolysis",`<div class="grid grid-3">${card("Clinical","Improvement in pain and hemodynamics supports reperfusion but is not sufficient alone.","blue")}${card("Electrical","Substantial ST-segment resolution and reperfusion arrhythmias can support successful reperfusion.","accent")}${card("Failure","Persistent pain, inadequate ST resolution, shock, or electrical instability should trigger rescue PCI.","danger")}</div>`)}
      ${tts("Special danger patterns",`<div class="grid grid-3">${card("Cardiogenic shock","Prompt revascularization is fundamental. Stabilization and revascularization planning occur together.","danger")}${card("Inferior MI + hypotension","Think of right-ventricular infarction; obtain right-sided leads and avoid indiscriminate preload reduction.","warn")}${card("Posterior occlusion","ST depression with tall R waves in V1–V3 may be reciprocal; record V7–V9 when suspected.","blue")}</div><div class="route-links">${routeButton("mi-localization","Localize the infarct")}${routeButton("complications","Recognize early complications")}</div>`)}
    `
  };

  modules["nste-acs"] = {
    title:"NSTEMI & unstable angina",
    search:"NSTE ACS NSTEMI unstable angina invasive strategy very high risk high risk dynamic ST changes GRACE",
    render:()=>`${hero({eyebrow:"Module 10",title:"NSTEMI & Unstable Angina",intro:"NSTE-ACS lacks persistent ST elevation, but it is not a low-stakes diagnosis. Risk is defined by hemodynamics, recurrent ischemia, arrhythmia, heart failure, troponin, ECG dynamics, and validated risk assessment.",chips:["No persistent ST elevation","Serial hs-cTn","Risk-based angiography","No fibrinolysis"],visual:"acute"})}
      ${tts("Invasive strategy by risk",`${table(["Risk profile","Typical approach"],[
        ["Very high risk","Immediate invasive evaluation for shock or hemodynamic instability, recurrent or refractory chest pain, life-threatening arrhythmia, mechanical complication, acute HF due to ongoing ischemia, or recurrent dynamic ST changes."],
        ["High risk","Early inpatient angiography is generally considered for confirmed NSTEMI, high risk scores, or significant dynamic ECG changes; exact timing is individualized."],
        ["Lower risk or uncertain diagnosis","Use validated hs-cTn pathways and structured risk assessment; use selective imaging or angiography according to findings."]
      ])}${callout("danger","Fibrinolysis is not used for NSTE-ACS","The absence of persistent ST elevation changes the reperfusion strategy. Treat with antithrombotic therapy and an invasive strategy matched to risk.")}`)}
      ${tts("Interactive urgency sorter",`<div class="interactive-panel" id="nste-sorter"><div class="choice-grid"><button class="choice-button" data-nste="shock">Hypotension, cool peripheries, pulmonary edema, and recurrent ST changes</button><button class="choice-button" data-nste="refractory">Recurrent pain despite therapy with dynamic ST depression</button><button class="choice-button" data-nste="confirmed">Stable patient with confirmed NSTEMI and elevated risk score</button><button class="choice-button" data-nste="low">Low-risk symptoms, non-ischemic serial ECGs, and validated hs-cTn rule-out pattern</button><button class="choice-button" data-nste="lysis">NSTEMI with very high troponin: give fibrinolysis</button></div><div class="result-box" id="nste-result"><h3>Select a presentation</h3><p class="muted">The tool classifies the urgency and identifies the unsafe option.</p></div></div>`)}
      ${tts("Unstable angina in the hs-troponin era",`<p>Unstable angina describes myocardial ischemia without an acute biomarker rise/fall above the assay-specific 99th percentile. With high-sensitivity assays, some patients previously called unstable angina are now classified as NSTEMI. The diagnosis still depends on symptoms, ECG, timing, and structured risk assessment.</p>${callout("warn","Normal ECG does not rule out NSTE-ACS","The ECG may be normal or non-diagnostic. Repeat tracings during symptoms and interpret them alongside serial troponin and clinical risk.")}`)}
      ${tts("Bleeding and ischemic risk must be balanced",`<div class="grid grid-2">${card("Ischemic-risk signals","Recurrent symptoms, dynamic ST–T change, troponin rise/fall, diabetes, renal dysfunction, LV impairment, prior CAD, and high clinical risk score.","danger")}${card("Bleeding-risk signals","Advanced age, prior bleeding, anemia, renal dysfunction, frailty, need for anticoagulation, and procedural factors.","warn")}</div><div class="route-links">${routeButton("acs-triage","Review troponin interpretation")}${routeButton("post-mi","Plan secondary prevention")}</div>`)}
    `
  };

  modules["mi-localization"] = {
    title:"MI types & ECG localization",
    search:"myocardial infarction type 1 type 2 ECG anterior inferior lateral posterior right ventricular leads LAD RCA LCx",
    render:()=>`${hero({eyebrow:"Module 11",title:"Myocardial Infarction: Type, Territory & ECG",intro:"MI is myocardial necrosis caused by ischemia. First establish that the injury is ischemic, then identify the mechanism and map the electrical territory to the likely culprit artery.",chips:["Type 1 MI","Type 2 MI","Anterior","Inferior","Posterior","Right ventricular"],visual:"ecg"})}
      ${tts("Universal concept",`<div class="grid grid-2">${card("Type 1 MI","Acute atherothrombosis after plaque rupture or erosion. Treatment targets coronary thrombosis and revascularization.","danger")}${card("Type 2 MI","Acute oxygen supply–demand imbalance without acute atherothrombosis, for example severe anemia, hypoxemia, hypotension, tachyarrhythmia, or severe hypertension. Treatment must address the trigger and the underlying coronary context.","warn")}</div>${callout("","Injury is not automatically infarction","Troponin elevation means myocardial injury. MI additionally requires evidence that ischemia caused the injury.")}`)}
      ${tts("ECG territory map",`${table(["Territory","Typical leads","Common culprit"],[
        ["Septal / anterior","V1–V4; extensive anterior may include V1–V6, I, and aVL","LAD"],
        ["Lateral","I, aVL, V5–V6","LCx or diagonal branch"],
        ["Inferior","II, III, aVF","RCA most often; LCx in some patients"],
        ["Posterior","Reciprocal ST depression and tall R waves in V1–V3; confirm with V7–V9","RCA or LCx"],
        ["Right ventricular","Right-sided leads, especially V4R, usually with inferior MI","Proximal RCA"]
      ])}`)}
      ${tts("Interactive ECG localization board",`<div class="interactive-panel"><p><b>Click a lead to reveal its main territorial association.</b></p><div class="ecg-map" id="ecg-map">${["I","II","III","aVR","aVL","aVF","V1","V2","V3","V4","V5","V6","V4R","V7–V9"].map(l=>`<button class="ecg-lead" type="button" data-lead="${l}">${l}</button>`).join("")}</div><div class="result-box territory-display" id="ecg-result"><h3>Select a lead</h3><p class="muted">Use contiguous lead groups and reciprocal patterns; never diagnose a territory from one isolated lead alone.</p></div></div>`)}
      ${tts("Right-ventricular infarction",`${callout("warn","Classic pattern","Inferior MI + hypotension + raised JVP + clear lungs should trigger suspicion. Obtain right-sided leads, avoid preload-reducing drugs if they worsen hypotension, and manage hemodynamics carefully.")}<div class="grid grid-3">${card("Preload dependence","The injured RV may require adequate filling pressure to maintain forward flow.","blue")}${card("Nitrates can be dangerous","Venodilation can sharply reduce preload and worsen hypotension.","danger")}${card("Look for conduction disease","Proximal RCA involvement can affect the AV node and produce bradyarrhythmia or block.","warn")}</div>`)}
      ${tts("ECG evolution",`<p>Hyperacute T waves may precede ST elevation. Q waves may develop but are not required for diagnosis. Reperfusion can accelerate ST resolution. Persistent ST elevation later may reflect ventricular aneurysm, ongoing ischemia, or another complication and must be interpreted clinically.</p><div class="route-links">${routeButton("stemi","Apply the reperfusion pathway")}${routeButton("complications","Use timing to identify complications")}</div>`)}
    `
  };

  modules.complications = {
    title:"MI complications",
    search:"myocardial infarction complications papillary muscle rupture VSD free wall rupture tamponade arrhythmia aneurysm Dressler timing",
    render:()=>`${hero({eyebrow:"Module 12",title:"MI Complications by Time & Pattern",intro:"Complications become easier to remember when linked to timing, anatomy, and the bedside pattern. Sudden deterioration, a new murmur, recurrent shock, or pulmonary edema after MI should trigger urgent imaging and specialist review.",chips:["Minutes to hours","First days","Days to weeks","Mechanical complications","Urgent echocardiography"],visual:"acute"})}
      ${tts("Timing map",`<div class="timeline"><div class="timeline-item"><span class="timeline-dot"></span>${card("Minutes to hours","Ventricular arrhythmia, bradyarrhythmia, acute heart failure, cardiogenic shock, and recurrent ischemia.<br><b>Clue:</b> sudden instability, low output, pulmonary edema, or arrest.","danger")}</div><div class="timeline-item"><span class="timeline-dot"></span>${card("First days","Papillary-muscle rupture, ventricular septal rupture, free-wall rupture/tamponade, acute pericarditis, and mural thrombus.<br><b>Clue:</b> new murmur, shock, EMD/PEA, or pleuritic pain.","warn")}</div><div class="timeline-item"><span class="timeline-dot"></span>${card("Days to weeks","LV aneurysm, thromboembolism, persistent HF, recurrent MI, and post-infarction pericarditis.<br><b>Clue:</b> persistent ST elevation, embolism, recurrent pain, or HF.","blue")}</div><div class="timeline-item"><span class="timeline-dot"></span>${card("Weeks to months","Remodeling, chronic HF, ventricular arrhythmia, and Dressler syndrome.<br><b>Clue:</b> progressive symptoms, late pericarditis/pleuritis, or arrhythmic events.","accent")}</div></div>`)}
      ${tts("Mechanical complications: pattern recognition",`${table(["Complication","Classic pattern","Why it is dangerous"],[
        ["Papillary-muscle rupture","Acute severe MR, flash pulmonary edema, shock; murmur may be soft when output is low","Abrupt volume overload and loss of forward stroke volume."],
        ["Ventricular septal rupture","New harsh pansystolic murmur with thrill, biventricular failure, and shock","Large acute left-to-right shunt and rapid hemodynamic collapse."],
        ["Free-wall rupture","Sudden tamponade, pulseless electrical activity, or death","Blood enters the pericardial space and prevents filling."],
        ["True LV aneurysm","Persistent ST elevation, HF, arrhythmia, or mural thrombus","Dyskinetic scar causes pump failure, arrhythmia, and embolic risk."],
        ["Pseudoaneurysm","Contained myocardial rupture, often with a narrow neck","High risk of complete rupture; urgent specialist evaluation."]
      ])}${callout("danger","Do not delay echocardiography","A new murmur, sudden heart failure, recurrent shock, or unexplained deterioration after MI requires urgent imaging and Heart Team or surgical evaluation.")}`)}
      ${tts("Interactive complication matcher",`<div class="interactive-panel" id="complication-lab"><div class="choice-grid"><button class="choice-button" data-complication="pmr">Day 3 after inferior MI: sudden pulmonary edema and shock; new systolic murmur may be soft</button><button class="choice-button" data-complication="vsr">Day 4 after MI: harsh pansystolic murmur, palpable thrill, biventricular failure</button><button class="choice-button" data-complication="fwr">Sudden collapse with PEA and tamponade physiology</button><button class="choice-button" data-complication="aneurysm">Weeks later: persistent ST elevation, HF, ventricular arrhythmia, or embolus</button><button class="choice-button" data-complication="dressler">Weeks later: fever and pleuritic or pericarditic pain</button></div><div class="result-box" id="complication-result"><h3>Select a presentation</h3><p class="muted">The result identifies the likely complication and the next urgent action.</p></div></div>`)}
      ${tts("Electrical and pump complications",`<div class="grid grid-3">${card("Ventricular arrhythmia","Treat instability immediately. Early ventricular arrhythmia reflects electrically unstable ischemic myocardium.","danger")}${card("Bradycardia or AV block","More common with inferior or RCA territory involvement; assess perfusion and the level of block.","warn")}${card("Cardiogenic shock","Look for extensive LV failure, RV infarction, mechanical rupture, or recurrent ischemia. Revascularization and hemodynamic support are time-sensitive.","blue")}</div><div class="route-links">${routeButton("mi-localization","Review territory clues")}${routeButton("post-mi","Move to recovery and prevention")}</div>`)}
    `
  };

  modules["post-mi"] = {
    title:"Post-MI prevention",
    search:"post myocardial infarction secondary prevention cardiac rehabilitation statin DAPT LVEF ICD lipid panel smoking cessation",
    render:()=>`${hero({eyebrow:"Module 13",title:"Post-MI Care & Secondary Prevention",intro:"Discharge is not the end of MI care. The next phase prevents reinfarction, sudden death, heart failure, bleeding, disability, and avoidable readmission.",chips:["Antithrombotic plan","Lipid lowering","LV protection","Cardiac rehabilitation","Follow-up"],visual:"prevention"})}
      ${tts("Discharge sequence",`<div class="flow-row"><div class="flow-step">Revascularization complete</div><div class="flow-step">LV function assessed</div><div class="flow-step">Bleeding + ischemic risk reviewed</div><div class="flow-step">Preventive therapy optimized</div><div class="flow-step">Cardiac rehabilitation</div><div class="flow-step">Follow-up + adherence</div></div>`)}
      ${tts("Core discharge domains",`${table(["Domain","Discharge priority"],[
        ["Antithrombotic plan","Specify aspirin/P2Y12 agent, intended duration, bleeding precautions, and interactions with anticoagulants."],
        ["Lipid management","Use high-intensity or maximally tolerated statin; reassess lipids after initiation or dose change and add non-statin therapy when indicated."],
        ["LV protection","Use ACE inhibitor/ARB/ARNI and an evidence-based beta-blocker when indicated; treat HF according to phenotype."],
        ["Sudden-death prevention","Reassess LVEF after recovery and guideline-directed therapy before primary-prevention ICD decisions, unless a secondary-prevention indication exists."],
        ["Lifestyle","Smoking cessation, Mediterranean-style dietary pattern, weight management, activity, sleep, and vaccination where appropriate."],
        ["Cardiac rehabilitation","Refer before discharge whenever possible; home-based options may improve access."],
        ["Return precautions","Recurrent chest discomfort, dyspnea, syncope, bleeding, palpitations, or HF symptoms require prompt evaluation."]
      ])}`)}
      ${tts("Contemporary lipid and DAPT points",`<div class="grid grid-2">${card("Lipid follow-up","The 2025 ACS guideline recommends a fasting lipid panel 4–8 weeks after starting or adjusting lipid-lowering therapy. Add a non-statin agent when LDL-C remains ≥70 mg/dL on maximally tolerated statin; further intensification may be reasonable at 55–69 mg/dL in selected high-risk patients.","accent")}${card("DAPT is individualized","Twelve months remains a default after ACS for patients without high bleeding risk, but shorter, de-escalated, or modified regimens may be appropriate when bleeding risk is high.","warn")}</div>`)}
      ${tts("Interactive discharge checklist",`<div class="interactive-panel" id="discharge-checklist"><p><b>Build a complete post-MI discharge plan.</b></p><div class="choice-grid">${["antithrombotic","lipid","lv","rehab","lifestyle","followup"].map((id,i)=>`<label class="choice-button"><input type="checkbox" data-discharge="${id}"> ${["Explicit antithrombotic plan and bleeding precautions","High-intensity lipid lowering and repeat lipid timing","LV function and HF/sudden-death plan","Cardiac rehabilitation referral","Smoking, diet, activity, weight, sleep, and adherence","Follow-up appointment and return precautions"][i]}</label>`).join("")}</div><div class="result-box"><div class="metric" id="discharge-score">0 / 6 complete</div><p id="discharge-note" class="muted">A safe discharge plan is both pharmacological and behavioral.</p></div></div>`)}
      ${tts("What patients should understand",`<ul class="check-list"><li>Which medicine prevents clotting, which lowers cholesterol, which protects the ventricle, and which controls symptoms.</li><li>Which bleeding signs require urgent review.</li><li>Why rehabilitation is part of treatment, not an optional extra.</li><li>Why medication adherence matters even when symptoms have disappeared.</li><li>Which recurrent symptoms should trigger emergency care.</li></ul><div class="route-links">${routeButton("clinical-lab","Practice complete cases")}${routeButton("flashcards","Start active recall")}</div>`)}
    `
  };

  const clinicalCases = [
    {title:"Predictable exertional pressure",vitals:["BP 138/82","HR 72","SpO₂ 98%"],stem:"A 58-year-old reports retrosternal pressure while climbing two flights of stairs. It resolves within 4 minutes of rest and has been unchanged for 6 months. Resting ECG is normal.",question:"Which pathway is most appropriate?",choices:["Immediate fibrinolysis","Chronic coronary syndrome assessment with risk evaluation and CCTA or stress imaging","Discharge without evaluation because the ECG is normal","Diagnose GERD because pain resolves"],answer:1,explanation:"The symptom pattern is stable and exertional. A normal resting ECG does not exclude coronary disease. Evaluate clinical likelihood, LV function, anatomy or inducible ischemia, and preventive risk factors."},
    {title:"Acute inferior MI with hypotension",vitals:["BP 82/58","HR 54","SpO₂ 95%"],stem:"A 64-year-old has 90 minutes of crushing chest pain. ECG shows ST elevation in II, III, and aVF. JVP is elevated and lungs are clear.",question:"What is the key additional diagnosis and immediate precaution?",choices:["Posterior pericarditis; give high-dose nitrate","Right-ventricular infarction; obtain V4R and avoid preload-reducing nitrates if hypotension worsens","Pulmonary edema; give routine morphine","NSTEMI; wait for troponin before reperfusion"],answer:1,explanation:"Inferior MI with hypotension, raised JVP, and clear lungs suggests RV infarction, usually from proximal RCA disease. Obtain right-sided leads and protect preload while activating reperfusion."},
    {title:"Troponin elevation during sepsis",vitals:["BP 92/60","HR 128","Temp 39.2°C"],stem:"A septic patient has a small dynamic troponin rise without ischemic chest pain or new ischemic ECG changes.",question:"Which statement is most accurate?",choices:["Every troponin rise is type 1 MI","This is acute myocardial injury; type 2 MI requires evidence that ischemia caused the injury","Fibrinolysis is mandatory","Troponin can be ignored in CKD or sepsis"],answer:1,explanation:"Troponin indicates myocardial injury. MI requires ischemic evidence. Sepsis and tachycardia can cause injury or type 2 MI depending on the full clinical context."},
    {title:"Day 3 pulmonary edema after MI",vitals:["BP 76/48","HR 118","SpO₂ 84%"],stem:"Three days after an inferior MI, a patient develops abrupt respiratory distress, flash pulmonary edema, and shock. A new systolic murmur is faint.",question:"Which complication is most likely?",choices:["Dressler syndrome","Papillary-muscle rupture causing acute severe MR","Stable LV aneurysm","Simple recurrent angina"],answer:1,explanation:"Papillary-muscle rupture can cause acute severe MR, pulmonary edema, and shock. The murmur may be soft when forward output is low. Urgent echocardiography and surgical evaluation are required."},
    {title:"Angina without obstructive arteries",vitals:["BP 124/76","HR 68","SpO₂ 99%"],stem:"A 49-year-old has recurrent exertional chest discomfort and objective ischemia. Angiography shows no flow-limiting epicardial stenosis.",question:"What is the best next conceptual step?",choices:["Dismiss the symptoms as anxiety","Consider microvascular dysfunction or vasospasm and pursue mechanism-based evaluation","Start fibrinolysis","Conclude that ischemia is impossible"],answer:1,explanation:"INOCA is clinically meaningful. Microvascular dysfunction, epicardial spasm, myocardial bridging, and other mechanisms may require targeted testing and therapy."},
    {title:"Late presentation with persistent ST elevation",vitals:["BP 116/72","HR 82","SpO₂ 97%"],stem:"Several weeks after a large anterior MI, the patient has persistent ST elevation and reduced LV function but no new pain.",question:"Which complication should be considered?",choices:["True LV aneurysm","Acute free-wall rupture","Unstable angina","Right-ventricular infarction"],answer:0,explanation:"A true LV aneurysm may cause persistent ST elevation, heart failure, ventricular arrhythmia, and mural thrombus. Clinical context distinguishes it from acute reinfarction."}
  ];

  modules["clinical-lab"] = {
    title:"Clinical reasoning lab",
    search:"clinical cases ischemic heart disease stable angina ACS RV infarction troponin papillary rupture INOCA",
    render:()=>`${hero({eyebrow:"Module 14",title:"Clinical Reasoning Lab",intro:"Use the whole pathway: identify stable versus acute, interpret ECG and troponin in context, choose the next test or treatment, and recognize complications from timing and physiology.",chips:["6 integrated cases","Immediate feedback","Mechanism-based explanations"],visual:"acute"})}
      <section class="section"><div class="section-head"><h2>Case deck</h2><span class="pill blue" id="case-counter">Case 1 of ${clinicalCases.length}</span></div><div class="card case-card" id="clinical-case"></div><div class="quiz-controls"><button class="secondary-button" id="prev-case" type="button">Previous case</button><button class="primary-button" id="next-case" type="button">Next case</button></div></section>
      ${tts("Reasoning template",`<div class="grid grid-4">${card("1 · Stability","Shock, ongoing ischemia, arrhythmia, heart failure, or mechanical complication?","danger")}${card("2 · Syndrome","Stable CCS, unstable angina, NSTEMI, STEMI, type 2 MI, or non-ischemic injury?","warn")}${card("3 · Evidence","Symptoms, serial ECGs, serial hs-cTn, echo, anatomy, and physiology.","blue")}${card("4 · Action","Reperfusion, invasive strategy, medical therapy, urgent imaging, or outpatient testing.","accent")}</div>`)}
      ${tts("Common exam traps",`<div class="grid grid-3">${card("Troponin trap","A positive troponin is not synonymous with type 1 MI.","warn")}${card("Nitrate trap","Response to nitrate does not prove a cardiac cause; nitrates may worsen RV-infarct hypotension.","danger")}${card("Normal-test trap","A normal resting ECG or echo does not exclude inducible ischemia.","blue")}${card("Murmur trap","A soft murmur can accompany severe mechanical failure when output is low.","danger")}${card("Vessel-count trap","PCI versus CABG is not chosen by vessel count alone.","warn")}${card("Non-obstructive trap","ANOCA/INOCA and MINOCA require mechanism-based evaluation, not dismissal.","accent")}</div><div class="route-links">${routeButton("flashcards","Reinforce with flashcards")}${routeButton("quiz","Take the full quiz")}</div>`)}
    `
  };

  const flashcards = [
    {tag:"Foundations",q:"Why does tachycardia worsen ischemia by two mechanisms?",a:"It increases myocardial oxygen demand and shortens diastole, reducing the time available for coronary perfusion."},
    {tag:"Anatomy",q:"Which artery usually supplies the inferior LV and AV node?",a:"The RCA in most people, although the LCx can supply the inferior territory in left-dominant anatomy."},
    {tag:"Anatomy",q:"What defines coronary dominance?",a:"The artery that gives rise to the posterior descending artery."},
    {tag:"Atherosclerosis",q:"What is the difference between fixed stenosis and plaque disruption?",a:"Fixed stenosis typically limits flow reserve and causes demand ischemia; rupture or erosion exposes thrombogenic material and can produce an acute thrombus."},
    {tag:"Stable angina",q:"What are the three classic historical criteria for typical angina?",a:"Retrosternal discomfort; provoked by exertion or emotional stress; relieved by rest or nitrate within minutes."},
    {tag:"Stable angina",q:"What makes a chronic symptom pattern unstable?",a:"New onset, crescendo severity or frequency, rest pain, prolonged episodes, hemodynamic compromise, or ischemic ECG change."},
    {tag:"Stable angina",q:"What is an anginal equivalent?",a:"An ischemic symptom such as exertional dyspnea, fatigue, nausea, diaphoresis, or epigastric discomfort occurring instead of classic chest pain."},
    {tag:"Testing",q:"Why can a normal resting echocardiogram not exclude ischemia?",a:"Resting function may be normal between episodes; inducible ischemia appears only under stress or during active ischemia."},
    {tag:"Testing",q:"What is the main role of CCTA in suspected chronic coronary disease?",a:"To define coronary anatomy and effectively exclude obstructive CAD in appropriately selected patients."},
    {tag:"Testing",q:"What do FFR and iFR answer?",a:"Whether an angiographic coronary lesion is physiologically significant and limits flow."},
    {tag:"Treatment",q:"What are the two separate goals of chronic coronary treatment?",a:"Prevent future cardiovascular events and relieve current ischemic symptoms."},
    {tag:"Treatment",q:"Which dangerous drug combination must be avoided with nitrates?",a:"Recent phosphodiesterase-5 inhibitor use because of the risk of profound hypotension."},
    {tag:"Treatment",q:"Why are beta-blockers not automatically lifelong for every chronic CAD patient?",a:"They relieve angina, but universal long-term prognostic benefit is not assumed without another indication such as recent MI, reduced LVEF, hypertension, or arrhythmia."},
    {tag:"Revascularization",q:"Name four variables that influence PCI versus CABG.",a:"Coronary anatomy and complexity, diabetes, LV function, surgical risk, expected completeness, comorbidity, and patient preference."},
    {tag:"Special syndromes",q:"What is INOCA?",a:"Ischemia with non-obstructive coronary arteries, often related to microvascular dysfunction or vasospasm."},
    {tag:"Special syndromes",q:"Why is MINOCA called a working diagnosis?",a:"Because the underlying cause still must be identified, such as plaque disruption, spasm, embolism, dissection, myocarditis, or Takotsubo syndrome."},
    {tag:"ACS",q:"What is the first ECG principle in suspected ACS?",a:"Obtain and interpret a 12-lead ECG as early as possible and repeat it when symptoms persist or the first tracing is non-diagnostic."},
    {tag:"ACS",q:"When should oxygen be given in ACS?",a:"For hypoxemia or respiratory distress, not routinely when oxygen saturation is normal."},
    {tag:"Troponin",q:"What is required to diagnose MI beyond an elevated troponin?",a:"A rise and/or fall with at least one value above the assay-specific 99th percentile plus clinical evidence of ischemia."},
    {tag:"Troponin",q:"What can cause acute troponin elevation without MI?",a:"Sepsis, tachyarrhythmia, pulmonary embolism, myocarditis, acute heart failure, and other causes of myocardial injury."},
    {tag:"STEMI",q:"Why must reperfusion not wait for troponin?",a:"An established STEMI or equivalent acute occlusion pattern is a clinical and ECG emergency; waiting increases infarct size."},
    {tag:"STEMI",q:"When is fibrinolysis considered?",a:"In selected early STEMI patients when timely PCI is not achievable and no contraindication exists, followed by transfer to a PCI-capable center."},
    {tag:"NSTE-ACS",q:"Is fibrinolysis used for NSTEMI or unstable angina?",a:"No. NSTE-ACS uses antithrombotic therapy and a risk-based invasive strategy."},
    {tag:"NSTE-ACS",q:"What makes NSTE-ACS very high risk?",a:"Shock, hemodynamic instability, recurrent or refractory pain, life-threatening arrhythmia, mechanical complication, acute HF due to ischemia, or recurrent dynamic ST changes."},
    {tag:"MI type",q:"What distinguishes type 1 from type 2 MI?",a:"Type 1 results from acute atherothrombosis; type 2 results from an ischemic supply–demand imbalance without acute atherothrombosis."},
    {tag:"ECG",q:"Which leads suggest inferior MI?",a:"II, III, and aVF."},
    {tag:"ECG",q:"Which finding suggests posterior MI on the standard 12-lead ECG?",a:"Reciprocal ST depression with tall R waves in V1–V3; confirm using V7–V9."},
    {tag:"RV infarction",q:"What is the classic bedside pattern of RV infarction?",a:"Inferior MI with hypotension, raised JVP, and clear lungs; confirm with right-sided leads such as V4R."},
    {tag:"Complications",q:"What does papillary-muscle rupture cause?",a:"Acute severe mitral regurgitation, flash pulmonary edema, and shock; the murmur may be soft if output is low."},
    {tag:"Complications",q:"What is the classic pattern of ventricular septal rupture?",a:"A new harsh pansystolic murmur with a thrill, biventricular failure, and shock."},
    {tag:"Complications",q:"What does free-wall rupture typically cause?",a:"Hemopericardium, tamponade, pulseless electrical activity, sudden collapse, or death."},
    {tag:"Complications",q:"How does a pseudoaneurysm differ from a true aneurysm?",a:"A pseudoaneurysm is a contained myocardial rupture with high rupture risk; a true aneurysm is scarred, thinned myocardium that can cause HF, arrhythmia, or thrombus."},
    {tag:"Post-MI",q:"When should lipids be rechecked after starting or adjusting therapy after ACS?",a:"Generally 4–8 weeks according to the 2025 ACC/AHA ACS guideline."},
    {tag:"Post-MI",q:"Why should LVEF be reassessed after recovery?",a:"For prognosis, heart-failure treatment, and timing of primary-prevention ICD decisions after guideline-directed therapy."},
    {tag:"Post-MI",q:"Why is cardiac rehabilitation part of treatment?",a:"It reduces recurrent risk and readmission while improving functional status, adherence, and quality of life."},
    {tag:"Exam trap",q:"Does relief with nitrate prove that pain is cardiac?",a:"No. Response to nitrate is neither sufficiently sensitive nor specific to diagnose ACS or angina."}
  ];

  modules.flashcards = {
    title:"Flashcards",
    search:"flashcards active recall ischemic heart disease cardiology",
    render:()=>`${hero({eyebrow:"Module 15",title:"Active-Recall Flashcards",intro:"Click a card—or focus it and press Enter or Space—to flip it. Filter by topic, shuffle the deck, and reset the orientation at any time.",chips:[`${flashcards.length} cards`,`True 3D flip`,`Keyboard accessible`,`Topic filters`],visual:"coronary"})}<section class="section"><div class="filter-bar" id="flashcard-filters"></div><div class="module-toolbar"><button class="secondary-button" id="shuffle-cards" type="button">Shuffle</button><button class="secondary-button" id="reset-cards" type="button">Reset cards</button><span class="muted" id="flashcard-count"></span></div><div class="flip-grid" id="flashcard-grid"></div></section>`
  };

  const quiz = [
    {q:"A patient has exertional retrosternal pressure that resolves after 5 minutes of rest and has not changed for months. What is the most appropriate initial classification?",choices:["Stable chronic coronary syndrome pattern","STEMI","Unstable angina by definition","Acute pericarditis"],answer:0,explanation:"The threshold and pattern are predictable and stable. The next step is structured chronic coronary assessment while remaining alert for any unstable features."},
    {q:"Why is tachycardia particularly harmful in coronary ischemia?",choices:["It reduces contractility only","It increases demand and shortens diastolic perfusion time","It always causes plaque rupture","It increases hemoglobin concentration"],answer:1,explanation:"Tachycardia raises work and oxygen demand while shortening the main phase of left-coronary perfusion."},
    {q:"Which finding most strongly indicates that a chest-pain pattern is unstable?",choices:["Same threshold for 12 months","Pain only during strenuous exercise","New rest pain with increasing frequency","Relief within 3 minutes of rest"],answer:2,explanation:"New, rest, crescendo, prolonged, or recurrent symptoms require an ACS pathway."},
    {q:"Which test best defines coronary anatomy non-invasively in an appropriate patient?",choices:["Resting ECG","CCTA","Troponin alone","Chest radiograph"],answer:1,explanation:"CCTA defines epicardial coronary anatomy and can effectively exclude obstructive CAD in selected patients."},
    {q:"Which statement about high-sensitivity troponin is correct?",choices:["Any elevation proves type 1 MI","One universal numeric threshold is valid for all assays","MI requires acute injury plus evidence of ischemia","Troponin is a screening test for stable angina"],answer:2,explanation:"Troponin elevation is myocardial injury. MI requires a rise/fall above the assay-specific 99th percentile plus ischemic evidence."},
    {q:"A patient took sildenafil recently and develops stable exertional angina. Which drug requires special avoidance?",choices:["Statin","Short-acting nitrate","Aspirin","ACE inhibitor"],answer:1,explanation:"Nitrates combined with recent PDE-5 inhibitors can cause profound hypotension."},
    {q:"Which situation tends to favor CABG over PCI?",choices:["Focal low-complexity lesion with high surgical risk","Diabetes with extensive complex multivessel disease","Patient preference for rapid recovery with equivalent outcomes","Single technically simple lesion"],answer:1,explanation:"Diabetes with extensive multivessel disease and complex anatomy often favors CABG when complete durable revascularization is expected."},
    {q:"A patient has ischemia with no flow-limiting epicardial stenosis. What should be considered?",choices:["Ischemia is impossible","Microvascular dysfunction or vasospasm","Fibrinolysis for all cases","Only anxiety"],answer:1,explanation:"INOCA may reflect coronary microvascular dysfunction, epicardial spasm, or other mechanisms."},
    {q:"In suspected ACS, which action should not be delayed?",choices:["Routine oxygen for normal saturation","Rapid 12-lead ECG","Waiting for all blood tests before examination","Morphine for every patient"],answer:1,explanation:"The ECG is central to identifying acute coronary occlusion and should be obtained as early as possible."},
    {q:"Which statement about oxygen in ACS is correct?",choices:["Give routinely to every patient","Use only after troponin rises","Use for hypoxemia or respiratory distress","Avoid even in severe hypoxemia"],answer:2,explanation:"Routine oxygen in normoxemic ACS is not recommended; use it when oxygenation or respiratory status requires it."},
    {q:"A clear STEMI pattern is present. What should happen before the troponin result?",choices:["Wait for confirmation","Activate reperfusion strategy","Order outpatient stress testing","Give fibrinolysis regardless of PCI availability"],answer:1,explanation:"Reperfusion must not wait for biomarker confirmation when the ECG and clinical setting establish acute occlusion."},
    {q:"Which therapy is not used for NSTEMI?",choices:["Aspirin","Anticoagulation","Risk-based invasive management","Fibrinolysis"],answer:3,explanation:"Fibrinolysis is not used for NSTE-ACS."},
    {q:"Which feature makes NSTE-ACS very high risk?",choices:["Stable symptoms with negative serial tests","Refractory pain with dynamic ST changes","Normal ECG and validated rule-out","Remote family history alone"],answer:1,explanation:"Refractory ischemia and dynamic ECG change require immediate invasive evaluation."},
    {q:"Which mechanism defines type 1 MI?",choices:["Sepsis without ischemia","Acute atherothrombosis","Chronic stable troponin elevation","Anemia alone without ischemic evidence"],answer:1,explanation:"Type 1 MI results from acute plaque disruption and coronary thrombosis."},
    {q:"ST elevation in II, III, and aVF localizes to which territory?",choices:["Anterior","Lateral","Inferior","Posterior only"],answer:2,explanation:"II, III, and aVF are the inferior leads, usually implicating the RCA or sometimes the LCx."},
    {q:"Inferior MI, hypotension, elevated JVP, and clear lungs suggest what?",choices:["Isolated LV aneurysm","Right-ventricular infarction","Papillary-muscle rupture only","Dressler syndrome"],answer:1,explanation:"The classic RV infarct pattern is inferior MI with preload-dependent hypotension, raised JVP, and clear lungs."},
    {q:"Three days after MI, a patient develops flash pulmonary edema and shock with a new soft systolic murmur. What is most likely?",choices:["Papillary-muscle rupture","Stable angina","Dressler syndrome","Chronic LV aneurysm"],answer:0,explanation:"Acute severe MR from papillary-muscle rupture may produce a soft murmur when cardiac output is low."},
    {q:"Which post-MI complication classically causes PEA and tamponade?",choices:["Ventricular septal rupture","Free-wall rupture","True LV aneurysm","Microvascular angina"],answer:1,explanation:"Free-wall rupture causes hemopericardium and tamponade, often presenting as sudden collapse or PEA."},
    {q:"What is a core post-MI discharge action?",choices:["Stop preventive medication once pain resolves","Refer to cardiac rehabilitation","Avoid checking LV function","Do not discuss bleeding precautions"],answer:1,explanation:"Cardiac rehabilitation is a core evidence-based part of secondary prevention."},
    {q:"Which statement is an exam trap?",choices:["A normal resting ECG can occur in chronic angina","Nitrate response proves the pain is cardiac","Troponin can rise outside MI","MINOCA requires further evaluation"],answer:1,explanation:"Relief with nitrate is not diagnostic of a cardiac cause."}
  ];

  modules.quiz = {
    title:"Exam quiz",
    search:"quiz MCQ ischemic heart disease cardiology exam",
    render:()=>`${hero({eyebrow:"Module 16",title:"Ischemic Heart Disease Exam Quiz",intro:"Twenty mixed questions test mechanisms, stable versus acute classification, investigations, medication safety, reperfusion, ECG localization, complications, and secondary prevention.",chips:[`${quiz.length} questions`,`Immediate explanations`,`Persistent score`],visual:"ecg"})}<section class="section"><div class="quiz-shell card" id="quiz-shell"></div></section>`
  };

  modules.sources = {
    title:"Sources & scope",
    search:"sources references ESC ACC AHA guidelines educational disclaimer",
    render:()=>`${hero({eyebrow:"Module 17",title:"Sources, Scope & Clinical Safety",intro:"The website reorganizes the uploaded study chapter into a connected interactive learning system and aligns its core terminology and management principles with contemporary ESC and ACC/AHA guidance.",chips:["Primary guidelines","Local source PDF","Educational use","No patient-specific protocol"],visual:"prevention"})}
      ${tts("Authoritative sources",`<div class="grid grid-2">${sources.map(s=>`<a class="card source-link" href="${s.url}" target="_blank" rel="noopener"><span class="source-id">${s.id}</span><h3>${s.title}</h3><p class="muted">${s.org}</p></a>`).join("")}</div>`)}
      ${tts("How the source chapter was transformed",`<div class="grid grid-3">${card("Reorganized","The original sequence was converted into 18 interconnected modules with explicit stable-versus-acute branching.","blue")}${card("Expanded","Added interactive supply–demand, symptom, test-selection, reperfusion, ECG, complication, and discharge tools.","accent")}${card("Made active","Added TTS, search, bookmarks, visit tracking, clinical cases, real flip cards, and a full quiz.","warn")}</div>`)}
      ${tts("Clinical disclaimer",`${callout("danger","Educational material only","Drug choice, dose, contraindications, reperfusion timing, invasive strategy, and post-MI decisions must follow the treating team, local protocol, and the patient's individual ischemic and bleeding risks.")}<p>Persistent or recurrent chest pressure, dyspnea, syncope, diaphoresis, shock, or an ischemic ECG requires emergency assessment. This website is not a diagnostic tool and does not generate patient-specific recommendations.</p>`)}
      ${tts("Keyboard and accessibility",`<ul class="check-list"><li>Press <b>/</b> to focus search.</li><li>Use Tab to move through controls.</li><li>Press Enter or Space to flip a focused flashcard.</li><li>Every content block has a speech button and bookmark button.</li><li>Theme, visited progress, bookmarks, and quiz state are stored only in the browser's local storage.</li></ul>`)}
    `
  };

  const allNavItems = navGroups.flatMap(g=>g.items);
  const searchIndex = allNavItems.map(item=>({id:item.id,title:modules[item.id].title,text:`${modules[item.id].search} ${modules[item.id].title}`}));

  window.IHDContent = {navGroups,modules,flashcards,quiz,clinicalCases,sources,searchIndex,hero,tts,callout,table,card,esc};
})();
